Repository durgakarituri23/Revive-Rewear, pull requests merged in 2024-11, with the labels that each got.

#14 Removed unrelated functionality
  frontend/src/pages/unapproved_products.js
Labels: invalid

#28 Implemented Dynamic Manage categories functionality
  backend/src/routes/category_routes.js
  backend/src/services/category_service.py
Labels: Feature development

#34 Refactored upload tab functionality
  backend/src/models/product.py
  backend/src/routes/product_routes.py
  backend/src/schemas/product_schema.py
  backend/src/services/product_service.py
  frontend/src/pages/uploadProduct.js
Labels: refactoring

#35 Developer
  backend/.env
  backend/src/config/auth_middleware.py
  backend/src/config/database.py
  backend/src/models/product.py
  backend/src/models/user.py
  backend/src/routes/auth_routes.py
  backend/src/routes/category_routes.js
  backend/src/routes/product_routes.py
  backend/src/schemas/product_schema.py
  backend/src/schemas/user_schema.py
  backend/src/services/auth_services.py
  backend/src/services/buyer_service.py
  backend/src/services/product_service.py
  frontend/src/App.js
  frontend/src/components/Header.js
  frontend/src/components/ProtectedRoute.js
  frontend/src/pages/AdminHome.js
  frontend/src/pages/HomeContent.js
  frontend/src/pages/SellerHome.js
  frontend/src/pages/adminRegister.js
  frontend/src/pages/login.js
  frontend/src/pages/manageCategories.py
  frontend/src/pages/manageProducts.js
  frontend/src/pages/uploadProduct.js
Labels: enhancement
